# Site settings
title: UnkL4b
description: ""
baseurl: "" # for test: remove string '/space-jekyll-template' to ''
url: "http://unkl4b.github.io/" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.githu.io'

# User settings
username: UnkL4b
user_title: UnkL4b
email: unkl4b@protonmail.com
twitter_username: UnkL4b
github_username: UnkL4b
#gplus_username:  
#linkedin_public_url: loremipsum # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
#disqus_username: loremipsum
#profile_picture: https://avatars0.githubusercontent.com/u/18489849
profile_picture: https://github.com/UnkL4b/unkl4b.github.io/blob/master/photo_2018-04-14_06-02-28.jpg?raw=true

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: Home
      url: /
      key_trigger: 1
    - title: Posts
      url: /posts
      key_trigger: 2
#    - title: series
#      url: /series
#      key_trigger: 3
#    - title: tags
#      url: /tags
#      key_trigger: 4
#    - title: about me
#      url: /about
#      key_trigger: 5
#  section_2:
#    - title: GitHub
#      url: http://www.github.com/unkl4b
#      new_tab: true
#      key_trigger: g
#    - title: Twitter
#      url: http://www.twitter.com/
#      key_trigger: t
#    - title: search
#      url: ""
#      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: GitMiner
    url: https://github.com/UnkL4b/GitMiner
  - name: Facebook Group Monitor
    url: https://github.com/UnkL4b/group-monitor
  - name: Nmap Parser XML
    url: https://github.com/UnkL4b/nmap-parser

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
